name: Deploy Laravel to Oracle Cloud

on:
  push:
    branches:
      - main  #  main 브랜치에 코드가 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest  #  GitHub Actions 가상 머신 (Ubuntu 환경)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        #  GitHub Actions 빌드 서버에 현재 저장소 코드를 가져옴

      # Github Action 가상 서버 접속
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        #  GitHub Secrets 에서 SSH 키를 가져와 SSH 접속을 위한 설정 진행

      # SSH 접근이 정상인지 체크 할때만 사용 정상작동시 주석처리
      - name: Debug SSH
        run: |
          ls -lah ~/.ssh
          cat ~/.ssh/id_rsa | head -n 5
          ssh -i ~/.ssh/id_rsa -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      # 오라클 서버에 등록
      - name: Deploy to Oracle Cloud
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/laravel_med  #  Laravel 프로젝트 폴더로 이동

            echo "Updating application..."
            git pull origin main  #  최신 코드 가져오기

            echo "Installing PHP dependencies..."
            composer install --no-dev --optimize-autoloader  # PHP 패키지 설치

            # echo "Installing Node.js dependencies…" #node
            # npm install  #  JavaScript 패키지 설치
            # npm run build  #  프론트엔드 빌드

            echo "Applying database migrations..."
            php artisan migrate --force  #  DB 마이그레이션 실행

            echo "Setting permissions for storage and cache..."
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            echo "Creating storage symbolic link..."
            rm -rf public/storage
            php artisan storage:link

            echo "Clearing cache..."
            php artisan config:clear  #  설정 캐시 삭제
            php artisan cache:clear   #  애플리케이션 캐시 삭제
            php artisan queue:restart #  큐 작업 재시작

            echo "Restarting Nginx..."
            sudo systemctl restart nginx  # Nginx 웹 서버 재시작
          EOF
        # 오라클 클라우드 서버에 SSH 로 접속 후 배포 명령어 실행

      - name: Cleanup SSH Key
        run: rm -rf ~/.ssh
        #  배포 후 보안 강화를 위해 SSH 키 삭제
